docs/getting-started.md

This pull request includes updates to the `docs/getting-started.md` file to reflect changes in the model registry URLs. The most important changes include updating the commands for building, pulling, pushing, and deleting model artifacts.
Updates to model registry URLs:
* Updated the `modctl build` command to use the new registry URL `registry.com/models/llama3:v1.0.0` instead of the old URL `127.0.0.1/library/test-models:v1`.
* Updated the `modctl pull` command to use the new registry URL `registry.com/models/llama3:v1.0.0` instead of the old URL `127.0.0.1/library/test-models:v1`.
* Updated the `modctl push` command to use the new registry URL `registry.com/models/llama3:v1.0.0` instead of the old URL `127.0.0.1/library/test-models:v1`.
* Updated the `modctl rm` command to use the new …

docs: change the registry address

---

cmd/extract.go
cmd/root.go
docs/getting-started.md
pkg/archiver/archiver.go
pkg/backend/backend.go
pkg/backend/build/build.go
pkg/backend/extract.go
pkg/backend/progress.go
pkg/backend/pull.go
pkg/backend/push.go
pkg/config/extract.go
pkg/config/pull.go

This pull request introduces several changes to enhance the functionality of the pull and push operations, as well as refactoring some parts of the codebase. The most significant changes include adding support for specifying an output path for exporting model artifacts, renaming and refactoring the `tar.go` file, and updating the progress bar style.
Enhancements to pull and push operations:
* [`cmd/pull.go`](diffhunk://#diff-d083b2621fc1453b30bfe075a3f58f2844ed7b124a62e0a86c284290d00511e4R50): Added a new flag `--output` to specify the output path for exporting the model artifact and updated the `runPull` function to handle this new configuration. [[1]](diffhunk://#diff-d083b2621fc1453b30bfe075a3f58f2844ed7b124a62e0a86c284290d00511e4R50) …

feat: support export to output path for pull command

---

cmd/pull.go
pkg/backend/options.go
pkg/backend/pull.go
pkg/config/pull.go

This pull request introduces a new feature to allow insecure connections for the pull operation by adding an option to skip TLS verification. The most important changes include updates to command flags, backend options, and the pull configuration.
* [`cmd/pull.go`](diffhunk://#diff-d083b2621fc1453b30bfe075a3f58f2844ed7b124a62e0a86c284290d00511e4R49): Added a new flag `--insecure` to use an insecure connection and skip TLS verification.
* [`pkg/backend/options.go`](diffhunk://#diff-1feaee55567fcf37e5d6098edc81dce8d36eb1952195d38c64d473dbd313bf20R42-R48): Added a new `WithInsecure` option to set the insecure flag in the backend options.
* [`pkg/config/pull.go`](diffhunk://#diff-da1524afd5700a24c5e4a753564c7597e11e083b80efb1eb4a710758c2398afaR22-R30): Updated the `Pull` struct to include the …

feat: add insecure options for pull

---

cmd/build.go
cmd/extract.go
cmd/inspect.go
cmd/list.go
cmd/login.go
cmd/logout.go
cmd/prune.go
cmd/pull.go
cmd/push.go
cmd/rm.go
cmd/root.go
pkg/backend/backend.go
pkg/config/root.go
pkg/storage/factory.go

This pull request includes several changes to the `modctl` command-line tool, primarily focusing on configuring and using a storage directory specified by the user. The most important changes include modifying backend initialization to accept a storage directory, updating command files to pass the storage directory, and adding a new configuration package to manage the root configuration.
Backend initialization:
* [`pkg/backend/backend.go`](diffhunk://#diff-c65bcfe9bb457434c3e69ba3f0576d7669935f350d24e2c2c58b05b4f9c510b2L64-R65): Modified the `New` function to accept a `storageDir` parameter.
* [`pkg/storage/factory.go`](diffhunk://#diff-a0f350ad9b077568317808a605403162b85e380ceb375d220b5c03b7d2cd461fL20-R40): Updated the `New` function to accept a `storageDir` parameter and removed …

feat: add storage dir for modctl

---

cmd/root.go

This pull request makes a small but important change to the `cmd/root.go` file. The change ensures that the `storage-dir` flag for `modctl` has a default value by setting it to the current value of `rootConfig.StoargeDir`.
* [`cmd/root.go`](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fL62-R62): Modified the `storage-dir` flag to use `rootConfig.StoargeDir` as the default value.

feat: add default storage dir for modctl

---

cmd/login.go
cmd/pull.go
cmd/push.go
pkg/backend/options.go
pkg/backend/pull.go
pkg/backend/push.go
pkg/config/pull.go
pkg/config/push.go

This pull request introduces several enhancements and refactorings to improve the concurrency and configuration handling of the `pull` and `push` commands. The most important changes include the addition of concurrency options, validation for configuration, and refactoring of backend options.
* Added a new concurrency option to the `pull` and `push` commands, allowing users to specify the number of concurrent operations. (`cmd/pull.go`, `cmd/push.go`, `pkg/config/pull.go`, `pkg/config/push.go`, `pkg/backend/options.go`) [[1]](diffhunk://#diff-d083b2621fc1453b30bfe075a3f58f2844ed7b124a62e0a86c284290d00511e4R41-R52) [[2]](diffhunk://#diff-e8011aeef8362327cdc0e4492778f39d0eb835e4cafe821111e3446637cc862eR41-R52) [[3]](diffhunk://#diff-1feaee55567fcf37e5d6098edc81dce8d36eb1952195d38c64d473dbd31 …

feat: add concurrency support for pull and push operations

---

pkg/backend/build.go
pkg/backend/extract.go
pkg/backend/processor/license.go
pkg/backend/processor/model.go
pkg/backend/processor/model_config.go
pkg/backend/processor/readme.go
pkg/storage/distribution/distribution.go

This pull request includes various fixes and improvements across multiple files in the `pkg/backend` and `pkg/storage` directories. The changes mainly focus on correcting typos, ensuring proper error handling, and updating import statements for better code organization.
* Corrected typos in error messages within the `Build` and `Extract` methods in `pkg/backend/build.go` and `pkg/backend/extract.go` respectively. [[1]](diffhunk://#diff-d6967c304021925580fe39f08821dc9e301bcc02a119e188d723e6939f170a5cL60-R68) [[2]](diffhunk://#diff-e1a825c6b4039fbae050899c58346ac2ad7bcd46f579e16b1b78fc5504848fddL55-R55)
* Updated error handling in the `Process` method for multiple processors (`licenseProcessor`, `modelProcessor`, `modelConfigProcessor`, and `readmeProcessor`) to return the actual error …

fix: build failed when registry address with port

---

cmd/pull.go
cmd/push.go
pkg/config/pull.go
pkg/config/push.go

This pull request includes changes to the concurrency settings and variable initialization for push and pull operations in the configuration files. The most important changes are as follows:
Concurrency settings:
* [`pkg/config/pull.go`](diffhunk://#diff-da1524afd5700a24c5e4a753564c7597e11e083b80efb1eb4a710758c2398afaL23-R23): Increased the default number of concurrent pull operations from 3 to 5.
* [`pkg/config/push.go`](diffhunk://#diff-7bc49abf8a6d1070cf8e9b2a0c971a719626d67c9ad709ea95bd432eddaa5644L23-R23): Increased the default number of concurrent push operations from 3 to 5.
Variable initialization:
* [`cmd/push.go`](diffhunk://#diff-e8011aeef8362327cdc0e4492778f39d0eb835e4cafe821111e3446637cc862eL30-R30): Changed the initialization of `pushConfig` from `config.NewPull()` to …

feat: change defaultPullConcurrency and defaultPushConcurrency to 5

---

pkg/backend/progress.go
pkg/backend/pull.go
pkg/backend/push.go

This pull request introduces an `Abort` method to the `ProgressBar` class and integrates it into various error handling scenarios within the `pullIfNotExist` and `pushIfNotExist` functions. The most important changes include the addition of the `Abort` method and its usage to handle errors more gracefully by aborting the progress bar when an error occurs.
Enhancements to error handling:
* [`pkg/backend/progress.go`](diffhunk://#diff-3e071d439de18fe4e494264841f0ea962b4d587a878e5af3761bea3f723c323fR108-R118): Added a new `Abort` method to the `ProgressBar` class to abort the progress bar for a given descriptor.
Integration of the `Abort` method in error scenarios:
* [`pkg/backend/pull.go`](diffhunk://#diff-f2435c0ad2b72cf7e41c9392804ffc2c7c29981c749a01127d335d228698ac00R166): Updated the …

fix: fix progress bar stuck when error occurred during pull/push

---

docs/getting-started.md
pkg/backend/build.go
pkg/backend/build/build.go
pkg/backend/build_test.go
pkg/backend/processor/base.go
pkg/backend/processor/license.go
pkg/backend/processor/license_test.go
pkg/backend/processor/model.go
pkg/backend/processor/model_config.go
pkg/backend/processor/model_config_test.go
pkg/backend/processor/model_test.go
pkg/backend/processor/processor.go
pkg/backend/processor/readme.go
pkg/backend/processor/readme_test.go

This pull request includes significant changes to the `backend` package, focusing on refactoring the processor logic and improving the `Build` function. The most important changes include the introduction of a `base` struct for processors, modifications to the `Build` function, and updates to the processor implementations and their corresponding tests.
* **Introduction of `base` struct for processors:**
- Added a new `base` struct in `pkg/backend/processor/base.go` to handle common processor logic, including the `Process` method.
- Updated `licenseProcessor`, `modelProcessor`, and `modelConfigProcessor` to utilize the new `base` struct for processing files. [[1]](diffhunk://#diff-8e6a212f2835c8e287099fa0b13b281f6c553a865fe0c7672d92562cddce36afL21-R47) …

refactor: change regex match to the glob path pattern

---

.goreleaser.yml

This pull request includes a small change to the `.goreleaser.yml` file. The change specifies the maintainer for the `modctl` package. 
* [`.goreleaser.yml`](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689R42): Added `Model Spec Maintainers <model-spec-maintainers@googlegroups.com>` as the maintainer for the `modctl` package.

chore: add maintainers for nfpms in .goreleaser.yml

---

.goreleaser.yml
cmd/root.go
cmd/version.go
pkg/version/platform_darwin.go
pkg/version/platform_linux.go
pkg/version/version.go

This pull request includes multiple changes to the `modctl` project, focusing on adding version information, initializing a new command, and updating build configurations. The most important changes include the addition of the `version` command, updates to `pkg/version` files, and modifications to the `.goreleaser.yml` configuration.
* Added `versionCmd` to `cmd/version.go` to display version information, including Git version, commit, platform, and build time. (`[cmd/version.goR1-R56](diffhunk://#diff-7cb26babce207ed9c17e9dd3ead0b66d204da3cf4d11649412c197defbb3029cR1-R56)`)
* Included `versionCmd` in the root command initialization in `cmd/root.go`. (`[cmd/root.goR70](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR70)`)
* Created …

feat: add version command for modctl

---

go.mod
go.sum
pkg/backend/build.go

This pull request includes updates to dependencies and improvements to error handling in the `backend` package. The most important changes are:
Dependency updates:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L6-R6): Updated the version of `github.com/CloudNativeAI/model-spec` from `v0.0.0-20250212030633-7aabe2b8eadc` to `v0.0.1`.
Error handling improvements:
* [`pkg/backend/build.go`](diffhunk://#diff-d6967c304021925580fe39f08821dc9e301bcc02a119e188d723e6939f170a5cR46-R49): Added a check to ensure the `tag` is not empty and returns an error if it is.

fix: check tag existence during build

---

pkg/backend/extract.go

This pull request includes changes to optimize the reading of blobs in the `pkg/backend/extract.go` file by introducing a buffered reader. The most important changes include adding a new import, defining a default buffer size, and modifying the `exportModelArtifact` function to use a buffered reader.
Buffer optimization:
* [`pkg/backend/extract.go`](diffhunk://#diff-e1a825c6b4039fbae050899c58346ac2ad7bcd46f579e16b1b78fc5504848fddR20): Added the `bufio` package import to enable buffered reading.
* [`pkg/backend/extract.go`](diffhunk://#diff-e1a825c6b4039fbae050899c58346ac2ad7bcd46f579e16b1b78fc5504848fddR33-R37): Defined a constant `defaultBufferSize` to set the buffer size for reading blobs to 4MB.
* [`pkg/backend/extract.go`](diffhunk://#diff-e1a825c6b4039fbae050899c58346ac2ad7bcd46f579e1 …

feat: add bufferedReader for extract

---

go.mod
go.sum
pkg/backend/build/build.go
pkg/backend/inspect.go
pkg/backend/inspect_test.go

This pull request includes several updates to the `modctl` module, primarily focusing on updating dependencies, simplifying code, and improving parameter handling in model configurations.
* Updated `github.com/CloudNativeAI/model-spec` dependency from version `v0.0.1` to `v0.0.2` in `go.mod`.
* Removed the unused `strconv` import from `pkg/backend/build/build.go`.
* Simplified the `buildModelConfig` function by directly assigning `ParamSize` from `modelfile` instead of parsing it from a string.
* Updated the `Inspect` function in `pkg/backend/inspect.go` to use `config.Config.ParamSize` directly, improving consistency and readability.

feat: align with the model-spec v0.0.2

---

pkg/archiver/archiver.go
pkg/archiver/archiver_test.go
pkg/backend/build/build.go
pkg/backend/extract.go

This pull request includes several improvements to the tar and untar functionality in the `archiver` package, as well as some enhancements in the backend build and extract processes. The most important changes include updating the `Tar` and `Untar` functions to handle directories and file paths more robustly, and adding file type checks in the build process.
Improvements to tar and untar functionality:
* [`pkg/archiver/archiver.go`](diffhunk://#diff-986cad88abd254d73a07b7666554aa9d84c8db3851c3084418ae24d8733c39ebL28-R127): Enhanced the `Tar` function to handle directories and preserve directory structures. Updated the `Untar` function to sanitize file paths and create necessary directories. [[1]](diffhunk://#diff-986cad88abd254d73a07b7666554aa9d84c8db3851c3084418ae24d8733c39ebL28-R127) …

fix: add the directory info to the tar header

---

cmd/build.go
go.mod
go.sum
pkg/backend/backend.go
pkg/backend/build.go
pkg/backend/build_test.go
pkg/backend/processor/base.go
pkg/backend/processor/code.go
pkg/backend/processor/doc.go
pkg/backend/processor/model.go
pkg/backend/processor/model_config.go
pkg/backend/processor/model_config_test.go
pkg/backend/processor/options.go
pkg/config/build.go
pkg/config/build_test.go
test/mocks/backend/backend.go

This pull request introduces several changes to the build process, including the addition of concurrency support and various improvements to the backend processing. The most important changes include adding concurrency options to the build command, updating the backend interface and implementation to support these options, and introducing new processor options.
* Added a new flag to specify the number of concurrent build operations (`cmd/build.go`).
* Updated the `runBuild` function to pass concurrency options to the backend (`cmd/build.go`).
* Modified the `Build` method in the `Backend` interface to accept additional options (`pkg/backend/backend.go`).
* Updated the `Build` method implementation to apply concurrency options (`pkg/backend/build.go`). …

feat: support concurrent for build operation(5 concurrency by default)

---

pkg/backend/pull.go
pkg/backend/push.go

This pull request includes changes to the backend's pull and push functionalities to enhance the reliability of HTTP client operations by incorporating retry mechanisms. The most important changes include adding a new import for the retry package and modifying the HTTP client initialization to use the retry transport.
Closes https://github.com/CloudNativeAI/modctl/issues/101
Enhancements to HTTP client reliability:
* [`pkg/backend/pull.go`](diffhunk://#diff-f2435c0ad2b72cf7e41c9392804ffc2c7c29981c749a01127d335d228698ac00R35): Added import for `retry` package (`oras.land/oras-go/v2/registry/remote/retry`) and modified the HTTP client initialization to use `retry.NewTransport` for handling retries during pull operations. [[1]](diffhunk://#diff-f2435c0ad2b72cf7e41c9392804ffc2c7c29981c749a0112 …

fix: add retry client for pull and push operation

---

cmd/root.go
go.mod
go.sum
pkg/backend/build/build.go
pkg/backend/processor/code_test.go
pkg/backend/processor/doc_test.go
pkg/backend/processor/model_config_test.go
pkg/backend/processor/model_test.go
pkg/backend/pull.go
pkg/storage/distribution/distribution.go
pkg/storage/storage.go
test/mocks/storage/storage.go

This pull request includes several changes to improve the handling of blob storage and signal handling in the application. The most important changes include modifications to the `PushBlob` method to accept an additional `ocispec.Descriptor` parameter, updates to the `go.mod` dependencies, and the addition of signal handling for graceful shutdown.
* [`pkg/storage/distribution/distribution.go`](diffhunk://#diff-68778df56737a4b452974ef6a28427d51587c4010306e3ae194ca75e9b6c9ed7L175-R203): Modified the `PushBlob` method to accept an additional `ocispec.Descriptor` parameter, allowing for more flexible blob storage operations.
* [`pkg/backend/build/build.go`](diffhunk://#diff-fca68706e95344e5665bfc23020fb22f71036dfd4b33800db12f962eff376643L59-R59): Updated calls to `PushBlob` to include the new …

optimize: improve pull process and switch the sha256 library to simd

---

cmd/list.go

This pull request includes a small but important change to the `cmd/list.go` file. The change modifies the output destination for the `tabwriter` from `os.Stderr` to `os.Stdout`.
Output destination change:
* [`cmd/list.go`](diffhunk://#diff-2cb6b39b26188bd68fce779dd82957aa4b969400c8a1554746a19f388924d9e5L66-R66): Changed the `tabwriter.NewWriter` output from `os.Stderr` to `os.Stdout` to ensure the output is directed to the standard output stream instead of the standard error stream.

fix: print the ls output to stdout

---

pkg/backend/push.go

This pull request includes an important change to the `pushIfNotExist` function in the `pkg/backend/push.go` file. The change ensures that when a descriptor is a manifest, the existence of the tag is also checked and handled appropriately.
Closes https://github.com/CloudNativeAI/modctl/issues/106
Key change:
* [`pkg/backend/push.go`](diffhunk://#diff-9dcd5308044bc9473f04358490f28c6748ec7bcf3cfa52058ef2756fb495846fR134-R145): Added logic to check for the existence of a tag when the descriptor is a manifest. If the tag does not exist or an error occurs while fetching the reference, the tag is pushed to the remote.

fix: push tag if the tag not bound to the existed manifest

---

cmd/generate.go

This pull request includes a minor change to the `cmd/generate.go` file to improve the consistency of flag naming conventions.
* [`cmd/generate.go`](diffhunk://#diff-d2b0f452bba73e3d2e556bae31fdf25c9c5375685adf1617bf27ceed1c66d031L51-R51): Changed the flag `ignore_unrecognized` to `ignore-unrecognized` to maintain consistency with other flag names.

fix: fix the mismatch cmd paramter name of modelfile generate

---

docs/getting-started.md
pkg/modelfile/command/command.go
pkg/modelfile/constants.go
pkg/modelfile/modelfile_test.go
pkg/modelfile/parser/parser.go
pkg/modelfile/parser/parser_test.go

This pull request includes changes to standardize the command names in the modelfile by converting them to uppercase. The changes affect documentation, command definitions, and test cases.
Standardization of command names:
* [`docs/getting-started.md`](diffhunk://#diff-31bcba2ccafa41d46fbbd6d1219f7f1e3b1fb3cad9faa8e4dc521bbb579dd7b3L42-R75): Updated the example modelfile to use uppercase command names.
* [`pkg/modelfile/command/command.go`](diffhunk://#diff-2c84a72fe01ba0d404e94e754b1e918637817ea2e2da15b510f251f04bb60cd5L25-R76): Modified command definitions to use uppercase names.
Test updates:
* [`pkg/modelfile/modelfile_test.go`](diffhunk://#diff-788328f65cd934d3abdc884aa8ac1a54671828118a0210389b221dbe4301e122L52-R63): Updated test cases to reflect the changes in command names to …

feat: update modelfile commands to uppercase format

---

pkg/storage/distribution/distribution.go

This pull request includes a couple of changes to the `pkg/storage/distribution/distribution.go` file, specifically aimed at improving error handling in the `StatBlob` function.
Improvements to error handling:
* [`pkg/storage/distribution/distribution.go`](diffhunk://#diff-68778df56737a4b452974ef6a28427d51587c4010306e3ae194ca75e9b6c9ed7R21): Added the `errors` package to handle error comparisons.
* [`pkg/storage/distribution/distribution.go`](diffhunk://#diff-68778df56737a4b452974ef6a28427d51587c4010306e3ae194ca75e9b6c9ed7R262-R266): Modified the `StatBlob` function to check if the error is `ErrBlobUnknown` and return `false, nil` if it is, improving the handling of blob not found scenarios.

fix: ignore the ErrBlobUnknown during stat blob

---

pkg/backend/build.go
pkg/backend/build/builder.go
pkg/backend/build/builder_test.go
test/mocks/backend/build/builder.go

This pull request focuses on enhancing the `BuildConfig` function by including layers as an additional parameter. This change impacts multiple files, including the main build logic, related tests, and mock implementations.
Closes: https://github.com/CloudNativeAI/modctl/issues/51
Key changes include:
* Modified `BuildConfig` to accept an additional `layers` parameter in `pkg/backend/build.go` and `pkg/backend/build/builder.go`. [[1]](diffhunk://#diff-d6967c304021925580fe39f08821dc9e301bcc02a119e188d723e6939f170a5cL81-R81) [[2]](diffhunk://#diff-8ffa00a0129cb498b64f761bd5c4133192873bb004e396b806ebd586ba2bb287L61-R62) [[3]](diffhunk://#diff-8ffa00a0129cb498b64f761bd5c4133192873bb004e396b806ebd586ba2bb287L151-R153)
* Updated `buildModelConfig` to process the `layers` parameter and include …

feat: padding the diff_ids in the model config

---

cmd/root.go

Fixes #122 
Updated `modctl` to show help on execution. rather than throwing errors.

feat: Show help on root cmd

---

cmd/build.go
cmd/push.go
pkg/backend/backend.go
pkg/backend/nydusify.go
pkg/config/build.go
pkg/config/push.go
test/mocks/backend/backend.go

This pull request introduces an experimental feature to "nydusify" model artifacts in both the build and push processes. The changes include updates to the configurations, command-line flags, and the implementation of the `Nydusify` function.
* Added a new `Nydusify` flag to the build and push configurations in `pkg/config/build.go` and `pkg/config/push.go` respectively. This flag is used to determine whether to nydusify the model artifact. [[1]](diffhunk://#diff-4fe11c9ce5925fd1222a68db9e81677689727dcf5e2ea068f7e2407671752adfR33) [[2]](diffhunk://#diff-7bc49abf8a6d1070cf8e9b2a0c971a719626d67c9ad709ea95bd432eddaa5644R29-R36)
* Updated the `init` functions in `cmd/build.go` and `cmd/push.go` to include the new `Nydusify` flag and mark it as hidden. …

feat: support nydusify for build and push

---

cmd/push.go
pkg/backend/push.go
pkg/config/push.go

This pull request introduces changes to the `push` command to add support for an insecure HTTP client configuration. The most important changes include updating the command-line flags, modifying the backend push functionality, and extending the configuration structure to include a new `Insecure` option.
* [`cmd/push.go`](diffhunk://#diff-e8011aeef8362327cdc0e4492778f39d0eb835e4cafe821111e3446637cc862eR54): Added a new command-line flag `--insecure` to disable TLS verification.
* [`pkg/backend/push.go`](diffhunk://#diff-9dcd5308044bc9473f04358490f28c6748ec7bcf3cfa52058ef2756fb495846fR22-R25): Imported the `crypto/tls` and `net/http` packages to support the new HTTP client configuration.
* [`pkg/backend/push.go`](diffhunk://#diff-9dcd5308044bc9473f04358490f28c6748ec7bcf3cfa52058ef2756fb49584 …

feat: add insecure flag for push command

---

pkg/backend/push.go

This pull request includes changes to the `pkg/backend/push.go` file to resolve an issue with pushing blobs and to enhance the code by importing the `io` package.
Improvements to blob pushing:
* [`pkg/backend/push.go`](diffhunk://#diff-9dcd5308044bc9473f04358490f28c6748ec7bcf3cfa52058ef2756fb495846fL181-R186): Wrapped the `reader` content with `io.NopCloser` to prevent errors when `Close()` is called, addressing issue [#50](https://github.com/CloudNativeAI/modctl/issues/50).
Code enhancement:
* [`pkg/backend/push.go`](diffhunk://#diff-9dcd5308044bc9473f04358490f28c6748ec7bcf3cfa52058ef2756fb495846fR25): Added the `io` package to the import section to support the use of `io.NopCloser`.

fix: resolve the EOF error during push

---

pkg/backend/build/builder.go
pkg/backend/build/builder_test.go
pkg/backend/build/local.go
pkg/backend/build/local_test.go
pkg/backend/build/remote.go
pkg/backend/extract.go
pkg/backend/pull.go
pkg/codec/codec.go
pkg/codec/raw.go
pkg/codec/tar.go

This pull request introduces significant changes to the `modctl` package, focusing on replacing the `archiver` package with a new `codec` package for encoding and decoding files. Additionally, it updates the `model-spec` dependency and refactors various functions to integrate the new codec system.
Dependency updates:
* Updated `github.com/CloudNativeAI/model-spec` from v0.0.2 to v0.0.3 in `go.mod`.
Refactoring and integration of codec package:
* Replaced `archiver` package with `codec` package in `pkg/backend/build/builder.go`. The `OutputLayer` method signature and the `BuildLayer` function were updated to use the new codec system for encoding files. [[1]](diffhunk://#diff-8ffa00a0129cb498b64f761bd5c4133192873bb004e396b806ebd586ba2bb287L29-R30) …

feat: add the codec support

---

.goreleaser.yml

This pull request includes a change to the `.goreleaser.yml` file to update the configuration for the `nfpms` section.
Configuration update:
* [`.goreleaser.yml`](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689L54-R54): Changed the `builds` key to `ids` in the `nfpms` section to correct the configuration.

chore: update the .goreleaser.yml

---

.golangci.yml
cmd/fetch.go
cmd/root.go
pkg/backend/backend.go
pkg/backend/fetch.go
pkg/backend/fetch_test.go
pkg/config/fetch.go

This pull request introduces a new `fetch` command to the `modctl` command-line tool, allowing users to fetch partial files from a remote repository. The most important changes include adding the `fetch` command implementation, updating the backend interface, and configuring the fetch operation.
* [`cmd/fetch.go`](diffhunk://#diff-1c38a74bd5b7032447686cc0bfafef491323991913a6d4e5aaf95e02f10c246cR1-R81): Added a new `fetch` command with various flags for configuration, including concurrency, plain HTTP, insecure connection, proxy, output directory, and patterns. The command validates the configuration and runs the fetch operation.
* [`cmd/root.go`](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR88): Registered the new `fetch` command with the root command. …

feat: introduce fetch command to get partial files

---

.golangci.yml
pkg/backend/prune.go
pkg/storage/distribution/distribution.go
pkg/storage/storage.go
test/mocks/backend/backend.go
test/mocks/storage/storage.go

This pull request introduces several changes to the backend and storage packages, primarily focusing on adding a new method for purging uploads and updating the mock functions accordingly. The most important changes include adding the `PerformPurgeUploads` method to the storage interface, updating the backend to call this new method, and adding mock functions for testing.
* [`pkg/backend/prune.go`](diffhunk://#diff-229183f255a5cb483afc1aaf14ab93924a43682fc42c88057c9911ebfb07caabR21-R34): Updated the `Prune` method to call the new `PerformPurgeUploads` method and handle errors appropriately.
* [`pkg/storage/distribution/distribution.go`](diffhunk://#diff-68778df56737a4b452974ef6a28427d51587c4010306e3ae194ca75e9b6c9ed7R319-R324): Added the `PerformPurgeUploads` method to perform purge …

fix: cleanup the purge uploads as well when running the prune command

---

cmd/login.go
pkg/backend/login.go
pkg/config/login.go

This pull request introduces support for insecure connections to the registry by adding a new `Insecure` flag and updating the relevant code to handle this new option. The most important changes include modifications to the command-line interface, backend login logic, and configuration structure.
* Added a new `--insecure` flag to the `login` command to allow insecure connections to the registry (`cmd/login.go`).
* Imported necessary packages for handling HTTP and TLS configurations (`pkg/backend/login.go`).
* Updated the `Login` function to configure the HTTP client with the `InsecureSkipVerify` option based on the new `Insecure` flag (`pkg/backend/login.go`).
* Added an `Insecure` boolean field to the `Login` struct to store the insecure connection option (`pkg/config/login.go`).
* …

feat: add --insecure for login command to skip tls verify

---

pkg/backend/attach.go
pkg/backend/build.go

This pull request includes changes to the `pkg/backend` package to improve the handling of model manifests and annotations. The key updates involve modifying the `BuildManifest` function calls and enhancing the annotation handling for model files.
Improvements to model manifest handling:
* [`pkg/backend/attach.go`](diffhunk://#diff-25a4006e1f7d4d1bb259002a032f3efe5f4b4dad94b8b3a2fccac02214301559L153-R153): Updated the `BuildManifest` function call to use `srcManifest.Annotations` instead of `manifestAnnotation()`.
* [`pkg/backend/build.go`](diffhunk://#diff-d6967c304021925580fe39f08821dc9e301bcc02a119e188d723e6939f170a5cR37-R41): Added a new constant `annotationModelfile` for the annotation key of the Modelfile.
Enhancements to annotation handling:
* …

feat: store the modelfile to the manifest annotation

---

docs/getting-started.md

This pull request updates the `docs/getting-started.md` file to include new commands for managing model artifacts more efficiently. The changes introduce options for building, pulling, and attaching model artifacts directly to and from remote repositories, which helps save local storage space.
New command options for storage efficiency:
* Added a command to build and push model artifacts directly to a remote registry, avoiding local storage strain (`docs/getting-started.md`).
* Introduced a command to pull and extract model artifacts directly from a remote repository into a specific directory, saving local disk space (`docs/getting-started.md`).
New commands for model artifact management:
* Added a `fetch` command to retrieve partial files from a model artifact using a file path glob …

docs: update the documentation for usage

---

pkg/backend/attach.go
pkg/backend/build.go
pkg/backend/build/builder.go
pkg/backend/build/interceptor/interceptor.go
pkg/backend/build/interceptor/nydus.go
pkg/codec/codec.go
pkg/codec/raw.go
pkg/codec/tar.go

This pull request introduces a new interceptor feature to the build process in the `pkg/backend` package. The changes include adding a new interceptor interface and implementing a specific interceptor called Nydus. The most important changes are summarized below:
* [`pkg/backend/attach.go`](diffhunk://#diff-25a4006e1f7d4d1bb259002a032f3efe5f4b4dad94b8b3a2fccac02214301559R303-R306): Added the interceptor option to the builder configuration and included logic to append the interceptor if `cfg.Nydusify` is enabled.
* [`pkg/backend/build.go`](diffhunk://#diff-d6967c304021925580fe39f08821dc9e301bcc02a119e188d723e6939f170a5cR71-R74): Similar changes as in `attach.go`, adding the interceptor option to the builder configuration.
* [`pkg/backend/build/interceptor/interceptor.go`](diffhunk://#diff-9 …

feat: support interceptor for build

---

cmd/root.go
pkg/config/root.go

This pull request introduces changes to enable and configure pprof for performance profiling in the application. The changes primarily affect the `cmd/root.go` and `pkg/config/root.go` files. The most important changes include adding pprof-related flags and initializing the pprof server if enabled.
Changes to enable and configure pprof:
* [`cmd/root.go`](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR20-R22): Imported necessary packages for pprof (`log`, `net/http`, and `net/http/pprof`).
* [`cmd/root.go`](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR44-R55): Added a `PersistentPreRunE` function to start the pprof server if the pprof flag is enabled.
* [`cmd/root.go`](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0 …

feat: support enable the pprof

---

pkg/backend/build/interceptor/nydus.go

This pull request updates the `mediaTypeChunkSizeMap` in the `nydus.go` file to include new media types for raw model weights and datasets. These changes ensure that the chunk size mapping accommodates additional media types.
* [`pkg/backend/build/interceptor/nydus.go`](diffhunk://#diff-9d895d1e8e4ae90ebe88eeb289fcbff9dcd21173fb3b5cd40492a46760102402R40-R42): Added `modelspec.MediaTypeModelWeightRaw` and `modelspec.MediaTypeModelDatasetRaw` to the `mediaTypeChunkSizeMap` with a chunk size of `64 * 1024 * 1024`.

feat(nydusify): support convert raw format of modctl artifact

---

pkg/backend/extract.go
pkg/backend/fetch.go
pkg/backend/pull.go
pkg/backend/pull_by_d7y.go
pkg/backend/push.go

This pull request introduces enhancements to the concurrency handling across several backend functions by integrating context-aware error groups. The changes ensure that goroutines respect context cancellation, improving the robustness and responsiveness of the application.
* Updated all functions (`Extract`, `Fetch`, `Pull`, `pullByDragonfly`, and `Push`) to use `errgroup.WithContext` instead of `errgroup.Group`, enabling context propagation and cancellation. (`pkg/backend/extract.go`: [[1]](diffhunk://#diff-e1a825c6b4039fbae050899c58346ac2ad7bcd46f579e16b1b78fc5504848fddL65-R74) `pkg/backend/fetch.go`: [[2]](diffhunk://#diff-7beefd1a4433544c6caa2cc7628ef65ced67356c1167954b1d93d32be2d234a3L85-R95) `pkg/backend/pull.go`: [[3]](diffhunk://#diff-f2435c0ad2b72cf7e41c9392804ffc2c7c29981c749a01 …

fix: cancel context when using errgroup for error return earlier

---

cmd/modelfile/modelfile.go
cmd/root.go
cmd/upload.go
go.mod
pkg/backend/attach.go
pkg/backend/attach_test.go
pkg/backend/backend.go
pkg/backend/build.go
pkg/backend/build/builder.go
pkg/backend/build/remote.go
pkg/backend/extract.go
pkg/backend/fetch.go
pkg/backend/inspect.go
pkg/backend/list.go
pkg/backend/login.go
pkg/backend/logout.go
pkg/backend/nydusify.go
pkg/backend/processor/base.go
pkg/backend/prune.go
pkg/backend/pull.go
pkg/backend/pull_by_d7y.go
pkg/backend/push.go
pkg/backend/rm.go
pkg/backend/tag.go
pkg/backend/upload.go
pkg/codec/codec.go
pkg/config/upload.go

This pull request introduces a new `upload` command, refines logging for various operations, and enhances the builder functionality with extended attribute (xattr) support for file metadata. It also includes minor dependency adjustments and code cleanups.
* Added a new `upload` command in `cmd/upload.go`, enabling users to upload files to a model artifact repository. This includes validation, flag support, and integration with the backend. (`[[1]](diffhunk://#diff-6833c134d800a5e41f7be71a3764d426179a965ec90addbbc4fb724ae4890c64R1-R75)`, `[[2]](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR145)`, `[[3]](diffhunk://#diff-c65bcfe9bb457434c3e69ba3f0576d7669935f350d24e2c2c58b05b4f9c510b2R37-R39)`)
* Replaced `logrus.Infof` with `logrus.Debugf` in …

feat: support the upload command and optimize the log

---

docs/getting-started.md

This pull request adds a new section to the `docs/getting-started.md` file, introducing the `upload` command for pre-uploading files to a repository to optimize build times.
Documentation update:
* Added a new "Upload" section to describe the `upload` command, which allows pre-uploading blobs to a repository to save overall build time. The example provided demonstrates uploading a file (`model-00001-of-00003.safetensors`) to a specified repository (`registry.com/models/llama3`).

docs: add the docs for upload command

---

pkg/backend/pull.go
pkg/backend/push.go

This pull request refactors the `Pull` and `Push` methods in the `pkg/backend` package to improve context handling by consistently using the `errgroup` context (`gctx`) instead of the parent context (`ctx`). This ensures proper cancellation and error propagation when using goroutines.
* `pkg/backend/pull.go`:
- Updated `Pull` method to replace all instances of `ctx` with `gctx` in goroutines, retries, and function calls to ensure consistent use of the `errgroup` context. [[1]](diffhunk://#diff-f2435c0ad2b72cf7e41c9392804ffc2c7c29981c749a01127d335d228698ac00L91-R110) [[2]](diffhunk://#diff-f2435c0ad2b72cf7e41c9392804ffc2c7c29981c749a01127d335d228698ac00L127-R127)
* `pkg/backend/push.go`:
- Updated `Push` method to replace all instances of `ctx` with `gctx` in goroutines, retries, and …

fix: errgroup context cancled after Wait

---

cmd/inspect.go
pkg/backend/backend.go
pkg/backend/inspect.go
pkg/backend/inspect_test.go
pkg/config/inspect.go
test/mocks/backend/backend.go

This pull request introduces a new feature to inspect the configuration of a model artifact and updates the `Inspect` method to return a more flexible data type (`any`). Key changes include adding a new `--config` flag, modifying the `Inspect` method's return type, and implementing logic to handle the new flag.
* [`cmd/inspect.go`](diffhunk://#diff-e1112a72d67ea1111e0c19d52bd341c23830344021f7f8534ffa74df2ad51d20R52): Added a new `--config` flag to allow users to inspect the configuration of a model artifact.
* [`pkg/config/inspect.go`](diffhunk://#diff-a0e57ac7281a88b8dd1ab4bf1b527e999d19980ca58b85c2091f37c06e4c6983R23-R31): Updated the `Inspect` struct to include a new `Config` field, with default initialization in the `NewInspect` function.
* …

feat: support inspect the config

---

pkg/backend/inspect.go
pkg/backend/inspect_test.go

This pull request introduces a new `MediaType` field to the `InspectedModelArtifactLayer` struct in `pkg/backend/inspect.go`. The changes ensure that the media type of model artifact layers is captured during inspection and validated in tests.
* Added a `MediaType` field to the `InspectedModelArtifactLayer` struct to store the media type of model artifact layers. (`pkg/backend/inspect.go`, [pkg/backend/inspect.goR60-R61](diffhunk://#diff-a94e5da4533561dba9ccbb2ab8b32d5c7952c5b3e6c2bfbd2a0a0cb901263388R60-R61))
* Updated the `Inspect` function to populate the `MediaType` field for each layer during inspection. (`pkg/backend/inspect.go`, [pkg/backend/inspect.goR119](diffhunk://#diff-a94e5da4533561dba9ccbb2ab8b32d5c7952c5b3e6c2bfbd2a0a0cb901263388R119))
* Enhanced the `TestInspect` function …

feat: add the MediaType of layer to inspected result

---

cmd/login.go
pkg/config/login.go
pkg/config/login_test.go
pkg/config/utils.go
pkg/config/utils_test.go

This pull introduces a new feature to pass login authentication information through a file. The key changes include adding a new `--authfile` flag in the login command to avoid exposing usernames and passwords during the CI/CD process.
- **cmd/login.go**: Add a `--authfile `flag to allow users to pass login authentication information through a file. Users can login through `modctl login --authfile=.dockerconfigjson.json example.io`.
- **pkg/config/login.go**: Update the Login struct to add a new AuthFilePath field with a default value of empty.
- **pkg/config/utils.go**: Added the parsing of username and password for dockerconfigjson format (https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets).
```
{
"auths": {
"my-registry.example:5000": {
"username": "tiger", …
```

feat: support using --authfile to login image repository

---

README.md

Adds a copyright field with the text require by the Linux Foundation. Feel free to move this to another part of the README if needed.
https://github.com/cncf/sandbox/issues/385
This adds the copyright field mentioned on the CNCF onboarding checklist issue above and outlined in the Contribution Agreement instructions doc.

Add CNCF copyright footer text

---

.github/workflows/e2e.yml

Add a new GitHub Actions workflow to automate end-to-end testing on push, pull requests, scheduled runs, and manual triggers. The workflow includes jobs to build the modctl binary, download the specified model from Hugging Face, and run tests using modctl.

ci: add GitHub Actions workflow for E2E testing

---

.github/workflows/e2e.yml

This pull request updates the authentication logic for the `modctl` login step in the end-to-end workflow. Now, the workflow uses a Personal Access Token (PAT) for authentication on pull request events, and falls back to the default `GITHUB_TOKEN` for other events.
Authentication logic improvements:
* [`.github/workflows/e2e.yml`](diffhunk://#diff-3e103440521ada06efd263ae09b259e5507e4b8f7408308dc227621ad9efa31eR144-R155): Added conditional logic to use the `CR_PAT` secret for `modctl` login during pull request events, and the `GITHUB_TOKEN` for all other events. This ensures appropriate credentials are used depending on the workflow trigger.

chore: use PAT token for pull request in e2e test

---

.github/workflows/e2e.yml

This pull request updates the GitHub Actions workflow configuration for end-to-end (E2E) tests. The main change is the removal of the workflow trigger for pull requests and the associated conditional authentication logic, simplifying the workflow to only run on pushes, scheduled events, and manual dispatches.
Workflow trigger changes:
* Removed the `pull_request` trigger from the `on:` section in `.github/workflows/e2e.yml`, so E2E tests will no longer run automatically on pull requests.
Authentication logic simplification:
* Removed conditional logic and Personal Access Token (PAT) authentication for pull requests in the E2E job steps; now, the workflow always uses the `GITHUB_TOKEN` for authentication.

ci(e2e): remove PR event and unify registry login

---

.github/workflows/lint.yml

This PR upgrades GolangCI-Lint to a newer version that includes support for Go 1.25.
- No functional code changes.

Chore: Upgrade GolangCI-Lint To Support Go1.25
